### ISSUE TITLE
Implement Unpaywall data model for publications with "best_url"

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#192]
Unpaywall has a more complex [data format/model](https://unpaywall.org/data-format) that we may want to use for our publication model, it includes "best OA location." 

One of the big issues to figure out is if we should be able to save an undetermined number of URLs for a publication, similar to what Unpaywall appears to have. They seem to serialize JSON array with URLs for this value and allow you to pull back a different number of Open access URLs with the attribute (or hash key) "best_url" being the way you may want to publish a specific one.

We could use similar or the same logic that Unpaywall uses for "best_url", for example do we prefer scholarsphere over anything else? How we decide best_url may is worth talking through with Ana.

Related discussion in Basecamp:  https://3.basecamp.com/4206247/buckets/15288919/messages/3979349792

## TODO

- [x] https://github.com/psu-stewardship/researcher-metadata/issues/256
- [x] https://github.com/psu-stewardship/researcher-metadata/issues/259
- [x] https://github.com/psu-stewardship/researcher-metadata/issues/260
- [x] https://github.com/psu-stewardship/researcher-metadata/issues/257
- [x] https://github.com/psu-stewardship/researcher-metadata/issues/261
- [x] https://github.com/psu-stewardship/researcher-metadata/issues/277

It probably makes the most sense for them to be implemented in the order listed above, although #257 could be worked on any time and concurrently with the others. It will definitely be important for #260 to be rolled out to production _after_ both #256 and #259.

**Comment by ajkiessl** [comment]
@EricDurante This all sounds good.  

I don't have a strong opinion on whether or not to delete or migrate the OAB data.  Since we'll be migrating the other OA urls, it should be pretty easy to migrate those with them.  My only concern is if you are tagging them in the `source` column (or whatever we end up calling it) as "Open Access Button", that might cause confusion in the future since their won't actually be an OAB import.  That might not be a big deal though.

Regarding the tagging of "best_url", do we want to default to what is in Unpaywall initially, then allow users and admins to change it later?
